/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Arrays;

public class Library {
    public int[] roll(int num) {
        if (num < 1) {
            return new int[] {};
        }
        int[] results = new int[num];
        for (int i = 0; i < num; i++){
            results[i] = (int) (Math.random() * 6) + 1;
        }
        return results;
    }

    public boolean containsDuplicates(int[] arr){
        outer: for (int o = 0; o < arr.length; o++){
            inner: for (int i = 0; i < arr.length; i++){
                if (o == i){
                    continue;
                } else if (arr[o] == arr[i]) {
                    return true;
                }
            }
        }
        return false;
        }

    public double arrayAverage(int[] arrIn){
        double total = 0;i)
        for (int num : arrIn){
            total += num;
        }
        System.out.println(total / arrIn.length);
        return total / arrIn.length;
    }

    public int[] arrayLowestAverage(int[][] arrs){
        int lowestIndex = 0;
        double lowestAverage = Double.POSITIVE_INFINITY;
        for (int i = 0; i < arrs.length; i++) {
            double avg = arrayAverage(arrs[i]);
            if (avg < lowestAverage) {
                lowestIndex = i;
                lowestAverage = avg;
            }
        }
        return arrs[lowestIndex];
    }
}
